server:
#  port: 8000 # TODO: 这个后续应该是网关的端口（现在是 admin 模块配的这个端口，admin 模块使用 HTTP 来调用 project 模块）
  port: 8001

spring: # 持久层配置文件
  application: # 服务发现配置，这个不要忘记加，注册一个服务名称
    name: short-link-project
  datasource: # ShardingSphere 配置
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml # ShardingSphere 配置文件路径（环境默认是 dev，这个参数可以通过 java -jar -database.env=dev 的方式去传入）
#  datasource: # 原数据库连接配置
#    username: root
#    password: 88888888
#    url: jdbc:mysql://127.0.0.1:3306/ohshortlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8 # 数据库连接配置
#    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动配置
#    hikari: # 数据库连接池，springboot 2.0 之后嵌入到官方组件规约中了，并且一些分库分表中间件对它的支持更友好
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud: # 服务发现配置
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

short-link:
  domain:
    default: surl.ink:8001
  stats: # 短链接统计地区信息访问配置
    locale:
      amap-key: dcc44afe5f0e8d0b6b91c5d3d53f7936 # 高德api应用key
  goto-domain: # 短链接白名单配置 TODO：风控这部分，看看后续能不能再加一个黑名单功能
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - baidu.com

mybatis-plus: # mybatis-plus 配置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
