server:
  port: 8003

# TODO：es 配置待测试
spring: # 持久层配置文件
  elasticsearch: # es 连接配置
    rest:
      uris: 127.0.0.1:9200 # 如果是多集群怎么办
      connection-timeout: 2s
      read-timeout: 30s

rocketmq:
  name-server: 127.0.0.1:9876 # 本地 mq 服务
  producer:
    # 必须指定 group
    group: ohshortlink_es_sync_pg # pg 表示生产者组
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1
    topic: es_sync_topic # 自定义的配置
  consumer:
     group: ohshortlink_es_sync_cg # cg 表示消费者组
