server:
  port: 8003

spring: # 持久层配置文件
  elasticsearch: # es 连接配置
    rest:
      uris: 127.0.0.1:9200 # 如果是多集群怎么办
      connection-timeout: 2s
      read-timeout: 30s

# 通过 dts 等工具将db数据同步过来，消费后写入es
#rocketmq:
#  name-server: common-rocketmq-dev.magestack.cn:9876 # 公用 rocketmq 服务
#  producer:
#    group: ohshortlink_project-service_stats-save_pg
#    topic: ohshortlink_project-service_topic
#    send-message-timeout: 2000
#    retry-times-when-send-failed: 1
#    retry-times-when-send-async-failed: 1
#  consumer:
#    group: ohshortlink_project-service_stats-save_cg
